### ISSUE TITLE
Password for db2inst1

### ISSUE THREAD

**Issue by sleicht** [bryantsai/db2-docker#1]
Hi

I read the scripts over and over but can't find another password than the default `db2inst1`. But somehow this doesn't work. Am I doing something wrong. Is there a way to set another password for my db2 user?

Thanks Stephan

**Comment by bryantsai** [comment]
It's in `create-inst.sh`, one of the `useradd` command.

**Comment by sleicht** [comment]
Yes, I saw it. But if I try connecting to the database I get following error:

```
db2inst1@db2_inst_1:~$ db2 connect to sample user db2inst1 using db2inst1
SQL30082N  Security processing failed with reason "24" ("USERNAME AND/OR
PASSWORD INVALID").  SQLSTATE=08001
```

Isn't this the password set by the script committed on `master`?

**Comment by zjuanma** [comment]
I have the same error.

**Comment by bryantsai** [comment]
Apparently I've been using `useradd` command's `-p` incorrectly for a long time ...

Now if you have base image created, you don't need to recreate the base. Just `clean-inst.sh` and then `create-inst.sh` should be enough.

**Comment by sleicht** [comment]
Thank you very much!
